# Generated by Django 5.1.2 on 2024-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('business', 'Business')], max_length=50)),
                ('lessons_count', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
    ]
