# Generated by Django 5.1.2 on 2024-11-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('paid', 'Paid Enrollment')], default='free_trial', max_length=20),
        ),
    ]
