# Generated by Django 5.1.2 on 2024-11-09 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_lesson_teacher_lesson_zoom_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_in_yen',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
