# Generated by Django 5.1.2 on 2024-11-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
